# POST http://608dev-2.net/sandbox/sc/team5/battle.py?user=20&game_id=2&profemon=SaraEllison

# POST http://608dev-2.net/sandbox/sc/team5/battle.py?user=42&game_id=2&profemon=AdamHartz

# GET http://608dev-2.net/sandbox/sc/team5/battle.py?user=20&game_id=2&init=true

# GET http://608dev-2.net/sandbox/sc/team5/battle.py?user=42&game_id=2&init=true&len=true

# POST http://608dev-2.net/sandbox/sc/team5/battle.py?user=20&game_id=2&move=Voltage Switch

# POST http://608dev-2.net/sandbox/sc/team5/battle.py?user=42&game_id=2&move=Recurse

# GET http://608dev-2.net/sandbox/sc/team5/battle.py?user=42&game_id=2

# GET http://608dev-2.net/sandbox/sc/team5/battle.py?user=20&game_id=2
